services:
  ch01:
    image: "clickhouse/clickhouse-server:latest"
    user: "101:101"
    container_name: ch01
    hostname: ch01
    volumes:
      - ./ch01/config.d:/etc/clickhouse-server/config.d
      - ./ch01/users.d:/etc/clickhouse-server/users.d
      - ch01_data:/var/lib/clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"

    depends_on:
      - keeper01
      - keeper02
      - keeper03
      - keeper04
      - keeper05

  ch02:
    image: "clickhouse/clickhouse-server:latest"
    user: "101:101"
    container_name: ch02
    hostname: ch02
    volumes:
      - ./ch02/config.d:/etc/clickhouse-server/config.d
      - ./ch02/users.d:/etc/clickhouse-server/users.d
      - ch02_data:/var/lib/clickhouse
    ports:
      - "8124:8123"
      - "9001:9000"

    depends_on:
      - keeper01
      - keeper02
      - keeper03
      - keeper04
      - keeper05

  ch03:
    image: "clickhouse/clickhouse-server:latest"
    user: "101:101"
    container_name: ch03
    hostname: ch03
    volumes:
      - ./ch03/config.d:/etc/clickhouse-server/config.d
      - ./ch03/users.d:/etc/clickhouse-server/users.d
      - ch03_data:/var/lib/clickhouse
    ports:
      - "8129:8123"
      - "9002:9000"

    depends_on:
      - keeper01
      - keeper02
      - keeper03
      - keeper04
      - keeper05

  keeper01:
    image: "clickhouse/clickhouse-keeper:latest-alpine"
    user: "101:101"
    container_name: keeper01
    hostname: keeper01
    volumes:
      - ./keeper01/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - keeper01_data:/var/lib/clickhouse-keeper
    ports:
      - "9181:9181"

  keeper02:
    image: "clickhouse/clickhouse-keeper:latest-alpine"
    user: "101:101"
    container_name: keeper02
    hostname: keeper02
    volumes:
      - ./keeper02/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - keeper02_data:/var/lib/clickhouse-keeper
    ports:
      - "9182:9181"

  keeper03:
    image: "clickhouse/clickhouse-keeper:latest-alpine"
    user: "101:101"
    container_name: keeper03
    hostname: keeper03
    volumes:
      - ./keeper03/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - keeper03_data:/var/lib/clickhouse-keeper
    ports:
      - "9183:9181"

  keeper04:
    image: clickhouse/clickhouse-keeper:latest-alpine
    user: "101:101"
    container_name: keeper04
    hostname: keeper04
    volumes:
      - ./keeper04/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - keeper04_data:/var/lib/clickhouse-keeper
    ports:
      - "9184:9181"

  keeper05:
    image: "clickhouse/clickhouse-keeper:latest-alpine"
    user: "101:101"
    container_name: keeper05
    hostname: keeper05
    volumes:
      - ./keeper05/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - keeper05_data:/var/lib/clickhouse-keeper
    ports:
      - "9185:9181"

volumes:
  ch01_data:
  ch02_data:
  ch03_data:
  keeper01_data:
  keeper02_data:
  keeper03_data:
  keeper04_data:
  keeper05_data:
